---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: elastic-glue
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: elastic-glue@sha256:ddfeda50e602f772d38dec77566d92c8ba0fcdb0787e65de2fa2a435e34fa0af
        namespace: offer-management
      name: 1.0.0.0
