---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: rtp-paymentreceived-glue
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: rtp-paymentreceived-glue@sha256:04d561edd63c067c7f3ab4c7a64e25435352955f5d704fb5a5f97afccbb210fb
        namespace: rtp-reference
      name: 1.0.0.0
