---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/git-commit: 3d717e8b08a3495a04bcf9c89dbb59795f751b30
      fabric8.io/git-branch: master
      fabric8.io/git-url: https://github.com/snandakumar87/customer-repository.git
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      app: elastic-glue
      provider: fabric8
      version: 1.0.0.0
      group: com.redhat
    name: elastic-glue
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: elastic-glue
      provider: fabric8
      group: com.redhat
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      fabric8.io/git-commit: 3d717e8b08a3495a04bcf9c89dbb59795f751b30
      fabric8.io/git-branch: master
      fabric8.io/git-url: https://github.com/snandakumar87/customer-repository.git
    labels:
      app: elastic-glue
      provider: fabric8
      version: 1.0.0.0
      group: com.redhat
    name: elastic-glue
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: elastic-glue
        provider: fabric8
        group: com.redhat
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 3d717e8b08a3495a04bcf9c89dbb59795f751b30
          fabric8.io/git-branch: master
          fabric8.io/git-url: https://github.com/snandakumar87/customer-repository.git
        labels:
          app: elastic-glue
          provider: fabric8
          version: 1.0.0.0
          group: com.redhat
      spec:
        containers:
        - env:
          - name: SPRING_APPLICATION_JSON
            value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: OFFER_TOPIC
            value: offer-output
          - name: CONSUMER_MAX_POLL_RECORDS
            value: "500"
          - name: CONSUMER_COUNT
            value: "1"
          - name: CONSUMER_SEEK_TO
            value: end
          - name: CONSUMER_GROUP
            value: elastic-glue
          - name: ACKS
            value: "1"
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: elastic-glue:1.0.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          resources:
            limits:
              cpu: "1.0"
              memory: 256Mi
            requests:
              cpu: "0.2"
              memory: 256Mi
          securityContext:
            privileged: false
